version: '3'

dotenv: ['.env']

vars:
  LOCAL_POSTGRES_DOCKER_NAME: localpostgres
  TEST_POSTGRES_DOCKER_NAME: testpostgres

tasks:
  # Tasks for local environment
  up-deps:
    desc: "Up dependencies."
    cmds:
      - docker run --name {{.LOCAL_POSTGRES_DOCKER_NAME}} -e POSTGRES_PASSWORD={{.POSTGRES_PASSWORD}} -p 5432:5432 -d postgres

  down-deps:
    desc: "Down dependencies"
    cmds:
      - |
        if docker ps -a --filter "name={{.LOCAL_POSTGRES_DOCKER_NAME}}" --format "{{.Names}}" | grep -w "{{.LOCAL_POSTGRES_DOCKER_NAME}}" > /dev/null; then
          docker stop {{.LOCAL_POSTGRES_DOCKER_NAME}}
          docker rm {{.LOCAL_POSTGRES_DOCKER_NAME}}
        else
          echo "Container {{.LOCAL_POSTGRES_DOCKER_NAME}} does not exist."
        fi

  restart-deps:
    desc: "Starts down-deps and up-deps"
    cmds:
      - go-task down-deps
      - go-task up-deps

  run-local:
    desc: "Starts locally. Beforehand need raise deps"
    cmds:
      - go run ./cmd
    env:
      CONFIG_PATH: ./config/config-local.yml

  # Tasks for tests
  unit-test:
    desc: "Starts unit tests"
    cmds:
      - go test -v ./internal/...

  test-up-deps:
    desc: "Up dependencies for tests."
    cmds:
      - docker run --name {{.TEST_POSTGRES_DOCKER_NAME}} -e POSTGRES_PASSWORD={{.POSTGRES_PASSWORD}} -p 9069:5432 -d postgres

  test-down-deps:
    desc: "Down dependencies for tests."
    cmds:
      - |
        if docker ps -a --filter "name={{.TEST_POSTGRES_DOCKER_NAME}}" --format "{{.Names}}" | grep -w "{{.TEST_POSTGRES_DOCKER_NAME}}" > /dev/null; then
          docker stop {{.TEST_POSTGRES_DOCKER_NAME}}
          docker rm {{.TEST_POSTGRES_DOCKER_NAME}}
        else
          echo "Container {{.TEST_POSTGRES_DOCKER_NAME}} does not exist."
        fi

  test-restart-deps:
    desc: "Starts down-deps and up-deps"
    cmds:
      - go-task test-down-deps
      - go-task test-up-deps

  test-run:
    desc: "Starts app for tests"
    cmds:
      - go run ./cmd
    env:
      CONFIG_PATH: ./config/config-tests.yml

  test:
    desc: "Need raise deps for tests and also run the app by following task: test-run. After tests all deps are need down"
    cmds:
      - go test -v ./tests/
    env:
      TEST_POSTGRES_DOCKER_NAME: testpostgres
      CONFIG_PATH: ./config/config-tests.yml

  # TODO: make commands for prod environment
  run-prod:
    cmds:
      - go run ./cmd
    env:
      CONFIG_PATH: ./config/config-prod.yml